import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MotivationQuotesService {

  constructor() { }

  GetQuote(): string {
    const list = this.getQuotes();
    const i = this.getRandomArbitrary(list.length)
    return list[i];
  }

  private getRandomArbitrary(max: number) {
    return Math.floor(Math.random() * max);
  }

  private getQuotes() {
    return [
      "If you’re not sore after your gym session or your brain’s not fried after a day of law, you’re doing it wrong.",
      "You either get the gains or the grades, or you’ll stay mediocre forever.",
      "Your weak body and lazy mind won’t get you through law school.",
      "Deadlifts don’t care about your excuses, and neither do examiners.",
      "Can’t handle the gym or the law? Then get used to failure.",
      "Leg day and case law are both non-negotiable.",
      "Why rest when your competition is outlifting and outstudying you?",
      "Skip leg day or skip the case studies, either way, you’re skipping success.",
      "Real winners don’t cry about sore muscles or sleepless nights.",
      "The only thing worse than failing your law exam is failing to squat your bodyweight.",
      "Sleep is for the weak. The strong study law and deadlift.",
      "If you’re not lifting heavy or studying hard, you’re wasting your potential.",
      "In law school and the gym, only the obsessed survive.",
      "Success in law and the gym is earned, not given.",
      "Your excuses won’t win court cases or build muscle.",
      "If it doesn’t hurt, you’re not doing it right – in law or in the gym.",
      "Stop complaining. There’s no sympathy for the weak in law school or the squat rack.",
      "If you can’t handle the pressure, quit now before law school and the gym destroy you.",
      "Failure is the result of weakness—physically in the gym, mentally in law.",
      "Work hard now or fail hard later – both in the gym and the courtroom.",
      "Lift heavy, study harder, or settle for mediocrity.",
      "You won’t win cases with weak arguments or weak muscles.",
      "If you’re not pushing your limits, you’re not serious about success.",
      "No one cares about your struggles. The bar exam and the barbell expect results.",
      "The bench press doesn’t care about your tiredness, and neither does your professor.",
      "The barbell and the law both require your dedication or nothing.",
      "Your GPA and your gains both depend on your grind.",
      "Toughen up—law school and the gym aren’t for the weak.",
      "You can either have a strong body and mind, or you can have excuses.",
      "Show me your grades and your PRs. Otherwise, your talk is meaningless.",
      "You’re only as strong as your will to study and train.",
      "Stop dreaming of success, start lifting and studying for it.",
      "Your muscles and your mind need the pain to grow.",
      "Success in law and fitness isn’t handed out, it’s earned with blood, sweat, and tears.",
      "Can’t handle the workload or the weights? Then you don’t deserve success.",
      "Complaining doesn’t change the fact that you’re weak—physically and mentally.",
      "Don’t ask for pity when you could be grinding in the gym or the library.",
      "Both the gym and law school punish laziness. You deserve what you tolerate.",
      "If you don’t have time for the gym or your studies, make time to fail.",
      "You don’t get a degree or a six-pack from sitting around.",
      "Exams and PRs aren’t waiting for you to be ready.",
      "Law school doesn’t care about your excuses, and neither do the weights.",
      "Lift until it hurts. Study until it hurts. Then keep going.",
      "Your competition is getting stronger in both mind and body while you’re slacking.",
      "If you’re tired, good. That means you’re finally working hard enough.",
      "You can sleep when your muscles and law degree speak for themselves.",
      "The barbell doesn’t care about your feelings, and neither does the bar exam.",
      "Don’t expect results if you’re not willing to suffer for them.",
      "You’ll either leave the gym and library stronger or weaker than when you entered.",
      "You can’t lift light and study easy, and expect great results.",
      "If you’re not exhausted, you haven’t worked hard enough.",
      "Pain now, results later. Or comfort now, failure forever.",
      "No breaks for the strong, only excuses for the weak.",
      "Your excuses won’t show up in court, and they won’t show up on the scale.",
      "Either the weights or the workload will break you, unless you break them first.",
      "Results don’t come from wishing, they come from lifting and learning.",
      "If you’re not pushing yourself, you’re falling behind.",
      "No one cares about your progress until you win cases and crush weights.",
      "When you slack off, someone else is beating you—both in the gym and the law.",
      "Lift heavier, study harder, or don’t bother at all.",
      "The grind isn’t pretty, but neither is failure.",
      "Weakness in the gym and the courtroom has the same result: failure.",
      "If you’re not dead tired, you’re not doing enough.",
      "What you skip today in the gym or law school, you’ll regret tomorrow.",
      "Your future self will either thank you or hate you.",
      "Either you outwork your competition, or they outwork you.",
      "If you don’t feel like quitting, you’re not working hard enough.",
      "The law doesn’t bend for the lazy, and neither do the weights.",
      "There’s no shortcut to success—only more work.",
      "Your diploma and your gains won’t arrive without sacrifice.",
      "Only losers look for the easy way out.",
      "Your mind and body are either growing or decaying.",
      "If you want results, stop asking for them and start grinding for them.",
      "Failure is an option—for the weak.",
      "No one got a six-pack or a law degree from sitting around.",
      "Weakness will always find a way to excuse itself.",
      "Comfort now means regrets later.",
      "Either you’re sore from the gym or sore from watching others succeed.",
      "Get out of your own way and start doing the work.",
      "You can’t lift heavy or argue well with a weak mind.",
      "No one owes you success—you earn it in sweat and late nights.",
      "You’ll either feel the pain of discipline or the pain of regret.",
      "No one respects someone who half-asses the gym or the law.",
      "Your future is determined by the reps you do and the chapters you read.",
      "Stop whining and start lifting—both weights and your GPA.",
      "Results come to those who don’t quit, no matter how hard it gets.",
      "The gym and law school only reward the relentless.",
      "Your future career and physique depend on what you do today.",
      "Complaining about hard work just proves you’re not cut out for it.",
      "Only the strong and the smart will succeed—choose to be both.",
      "You’ll either grow stronger or stay weak—mentally and physically.",
      "If you can’t handle the burn, you can’t handle success.",
      "No one ever got a law degree or six-pack by staying comfortable.",
      "You’re either working on your goals or watching someone else achieve them.",
      "Do more. Work harder. Lift heavier. There’s no other way.",
      "Only losers look for shortcuts in the gym or law school.",
      "You can’t expect results if you don’t put in the reps.",
      "Success is reserved for those who suffer through the pain.",
      "Weak body, weak mind. Strong body, strong mind. Choose wisely.",
      "You’ll either leave law school and the gym victorious, or broken.",
      "Excuses don’t win cases or build muscle.",
      "Your results are directly proportional to your effort—always.",
      "The grind doesn’t care how you feel.",
      "If it doesn’t challenge you, it doesn’t change you.",
      "You’ll never get anywhere with weak arguments or weak lifts.",
      "Work until your brain and body have nothing left to give.",
      "You can rest when your competition has stopped.",
      "If you’re not sweating in the gym and the library, you’re not winning.",
      "The pain of failure lasts longer than the pain of discipline.",
      "You’re either fighting for success or making excuses for failure.",
      "Laziness kills both grades and gains.",
      "No one’s impressed by excuses, only by results.",
      "Train your body and brain like your future depends on it—because it does.",
      "Nothing good comes easy—especially not law school or lifting.",
      "You’re either improving or getting worse—there’s no in-between.",
      "You’ll never achieve greatness by staying in your comfort zone.",
      "You don’t deserve success unless you’ve earned it through suffering.",
      "If you’re not exhausted, you haven’t worked hard enough.",
      "No one cares about your excuses, only your results.",
      "Failure is always an option—if you’re weak enough to accept it.",
      "Don’t just survive law school and the gym—dominate them.",
      "Pain now means progress later.",
      "You’ll either grow or quit—choose growth.",
      "Your diploma and your muscles both require suffering.",
      "You’re only as strong as your willpower.",
      "Only the relentless will achieve greatness.",
      "Weakness is a choice.",
      "You can either win or whine, but you can’t do both.",
      "Don’t talk about results—go out and get them.",
      "Nothing worth having comes without pain.",
      "You’ll never get anywhere with half-hearted effort.",
      "Stop being average—start becoming unstoppable.",
      "No one respects weakness in the gym or in the courtroom.",
      "Comfort now will cost you success later.",
      "Your goals require more than you think you can give—so give more.",
      "Winners don’t whine, they work.",
      "Push your limits or accept mediocrity.",
      "The more you suffer, the stronger you become.",
      "Your future success depends on today’s sacrifices.",
      "Succeeding in law and fitness is simple—just outwork everyone else.",
      "You’ll never grow stronger if you don’t embrace the pain.",
      "No one’s impressed by talk—only by results.",
      "Excuses are for the weak.",
      "Your GPA and your PRs don’t care about your comfort.",
      "You’ll never achieve greatness without pushing yourself to the limit.",
      "Stop being soft and start being unstoppable.",
      "You can either have success or excuses, not both.",
      "No one ever achieved anything great by staying in their comfort zone.",
      "You’ll never succeed if you’re not willing to suffer.",
      "Every rep and every case brings you closer to greatness.",
      "Winners don’t find excuses, they find ways to win.",
      "If you’re not pushing yourself, you’re falling behind.",
      "No one cares how tired you are—just get it done.",
      "You’ll never grow stronger by avoiding the struggle.",
      "Stop looking for shortcuts—there aren’t any.",
      "Only the strong-willed will succeed.",
      "The grind isn’t pretty, but neither is failure.",
      "Don’t expect results without sacrifice.",
      "You’re either growing or decaying.",
      "You’ll never achieve anything great by staying comfortable.",
      "Success comes to those who embrace the struggle.",
      "Winners keep going when everyone else quits.",
      "The gym and the law reward the relentless.",
      "Your competition is working harder—are you?",
      "Your muscles and your mind need the pain to grow.",
      "Don’t expect sympathy—just results.",
      "No one cares about your struggles—only your successes.",
      "Your excuses won’t win cases or build muscle.",
      "You’ll either feel the pain of discipline or the pain of regret.",
      "Lift heavier, study harder, or don’t bother at all.",
      "If you’re not exhausted, you haven’t worked hard enough.",
      "Results don’t come from wishing—they come from grinding.",
      "Your future success depends on today’s sacrifices.",
      "Comfort now means regrets later.",
      "No one got anywhere by staying in their comfort zone.",
      "You can either have excuses or results—not both.",
      "Every struggle makes you stronger.",
      "Your future self will thank you for the suffering you endure today.",
      "The only thing standing between you and success is your own weakness.",
      "Stop talking about it—start doing it.",
      "Your body and mind will only grow through struggle.",
      "The grind doesn’t stop until you succeed.",
      "If you want results, you’ll have to suffer for them.",
      "Winners don’t make excuses—they make results.",
      "You’ll either feel the pain of discipline or the pain of regret.",
      "Your excuses don’t matter—only your results do.",
      "No one got strong or smart by staying comfortable.",
      "The barbell and the law both require your dedication—or nothing.",
      "Excuses are just reasons for failure.",
      "You’re either growing stronger or growing weaker.",
      "No one’s impressed by excuses—only by results.",
      "Stop dreaming of success and start suffering for it.",
      "Every rep and every case brings you closer to greatness.",
      "You’re either winning or making excuses—choose wisely.",
      "You’ll never achieve anything by staying comfortable.",
      "Don’t expect results if you’re not willing to suffer for them.",
      "Only the strong and relentless succeed.",
      "Excuses don’t get results—only effort does.",
      "You can either complain about it or work harder.",
      "If you’re not exhausted, you haven’t worked hard enough."
    ]
  }
}
