import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MotivationQuotesService {

  constructor() { }

  GetQuote(): string {
    const list = this.getQuotes();
    const i = this.getRandomArbitrary(list.length)
    return list[i];
  }

  private getRandomArbitrary(max: number) {
    return Math.floor(Math.random() * max);
  }

  private getQuotes() {
    return [
      // Study/Law School Motivation
      "Success is the result of hard work, not just luck.",
      "The only way to succeed is through relentless effort.",
      "Don't just study to pass; study to master the subject.",
      "The law isn't forgiving to those who take shortcuts.",
      "Each day you procrastinate is another day closer to failure.",
      "Every hour spent studying brings you one step closer to your goals.",
      "Success doesn't happen overnight, but through perseverance.",
      "Your competition isn't resting. Neither should you.",
      "Don't aim for average; strive for excellence.",
      "Knowledge is power, and the more you gain, the stronger you become.",
      "Failure is temporary, but the lessons are permanent.",
      "If you don’t make sacrifices for your dream, your dream will become the sacrifice.",
      "The only way to finish is to start. Don't wait.",
      "No one will hand you success; you have to earn it.",
      "Your future self is watching you. Do your best.",
      "Don't be afraid of hard work. Be afraid of living an average life.",
      "The law is complex, and only those who work hard can truly master it.",
      "You can either let the challenges break you or build you.",
      "Stay focused; distractions will only delay your success.",
      "Success comes to those who are willing to go after it.",
      "It's not about how much you study, but how well you understand.",
      "Never give up; the harder the struggle, the sweeter the victory.",
      "You didn't come this far to only come this far.",
      "The more you prepare, the less you'll fear the challenge.",
      "You control your future, so don't let laziness rob you of your success.",
      "Excellence is the result of consistently applying discipline and effort.",
      "If you're not making mistakes, you're not learning enough.",
      "A little progress each day adds up to big results.",
      "You have the power to create your own opportunities.",
      "The only limits that exist are the ones you create.",
      "Don't stop when you're tired. Stop when you're done.",
      "The road to success is paved with hard work and determination.",
      "Believe in yourself, even when no one else does.",
      "The best preparation for tomorrow is doing your best today.",
      "Every challenge is an opportunity to improve.",
      "The competition is fierce. Be fiercer.",
      "Each hour you invest brings you closer to your goal.",
      "Be relentless in your pursuit of knowledge.",
      "The time for excuses is over. Now is the time to learn.",
      "Your studies will not shape you, they will either break you or strengthen you.",
      "The challenges you face are the tests of your character.",
      "Never lose faith in your abilities.",
      "Be the lawyer you would want for yourself.",
      "The time is now. Don’t let any opportunity slip away.",
      "Every hour you sleep is an hour you give to your competition.",
      "If you're not willing to put in the work, you'll regret it.",
      "Real lawyers aren't afraid of hard work.",
      "The only way to win in law school is to never give up.",
      "Hard work and dedication are the keys to success.",
      "If you fail in law school, you fail in life.",
      "The laws are not simple. Work to understand them.",
      "You are not alone. Everyone struggles. Be better than the rest.",
      "If you give up, you will forever live in the shadow of your dreams.",
      "Every case is an opportunity to grow and learn.",
      "Don't stop fighting just because it's hard.",
      "Success is the result of persistence and hard work.",
      "Never look back. The road forward is the only one that matters.",
      "If you don't fight for your dreams, you'll work for the dreams of others.",
      "The best lawyer is the one who never settles for less.",
      "The greatest successes come from those who face their challenges head-on.",
      "The challenges in law school are the stairs to your success.",
      "There are no shortcuts to success. Work hard!",
      "Success is the result of hard work, not just luck.",
      "The only way to succeed is through relentless effort.",
      "Don't just study to pass; study to master the subject.",
      "The law isn't forgiving to those who take shortcuts.",
      "Each day you procrastinate is another day closer to failure.",
      "Every hour spent studying brings you one step closer to your goals.",
      "Success doesn't happen overnight, but through perseverance.",
      "Your competition isn't resting. Neither should you.",
      "Don't aim for average; strive for excellence.",
      "Knowledge is power, and the more you gain, the stronger you become.",
      "Failure is temporary, but the lessons are permanent.",
      "If you don’t make sacrifices for your dream, your dream will become the sacrifice.",
      "The only way to finish is to start. Don't wait.",
      "No one will hand you success; you have to earn it.",
      "Your future self is watching you. Do your best.",
      "Don't be afraid of hard work. Be afraid of living an average life.",
      "The law is complex, and only those who work hard can truly master it.",
      "You can either let the challenges break you or build you.",
      "Stay focused; distractions will only delay your success.",
      "Success comes to those who are willing to go after it.",
      "It's not about how much you study, but how well you understand.",
      "Never give up; the harder the struggle, the sweeter the victory.",
      "You didn't come this far to only come this far.",
      "The more you prepare, the less you'll fear the challenge.",
      "You control your future, so don't let laziness rob you of your success.",
      "Excellence is the result of consistently applying discipline and effort.",
      "If you're not making mistakes, you're not learning enough.",
      "A little progress each day adds up to big results.",
      "You have the power to create your own opportunities.",
      "The only limits that exist are the ones you create.",
      "Don't stop when you're tired. Stop when you're done.",
      "The road to success is paved with hard work and determination.",
      "Believe in yourself, even when no one else does.",
      "The best preparation for tomorrow is doing your best today.",
      "Every challenge is an opportunity to improve.",
      "The competition is fierce. Be fiercer.",
      "Each hour you invest brings you closer to your goal.",
      "Be relentless in your pursuit of knowledge.",
      "The time for excuses is over. Now is the time to learn.",
      "Your studies will not shape you, they will either break you or strengthen you.",
      "The challenges you face are the tests of your character.",
      "Never lose faith in your abilities.",
      "Be the lawyer you would want for yourself.",
      "The time is now. Don’t let any opportunity slip away.",
      "Every hour you sleep is an hour you give to your competition.",
      "If you're not willing to put in the work, you'll regret it.",
      "Real lawyers aren't afraid of hard work.",
      "The only way to win in law school is to never give up.",
      "Hard work and dedication are the keys to success.",
      "If you fail in law school, you fail in life.",
      "The laws are not simple. Work to understand them.",
      "You are not alone. Everyone struggles. Be better than the rest.",
      "If you give up, you will forever live in the shadow of your dreams.",
      "Every case is an opportunity to grow and learn.",
      "Don't stop fighting just because it's hard.",
      "Success is the result of persistence and hard work.",
      "Never look back. The road forward is the only one that matters.",
      "If you don't fight for your dreams, you'll work for the dreams of others.",
      "The best lawyer is the one who never settles for less.",
      "The greatest successes come from those who face their challenges head-on.",
      "The challenges in law school are the stairs to your success.",
      "There are no shortcuts to success. Work hard!",

      // Life Improvement/Motivation
      "You're not here to play. You're here to win. Do it or leave it.",
      "If you're not ready to give it your all, you'll never succeed.",
      "Success is no accident. It's the price for your sleepless nights.",
      "The world is a tough place. If you don’t fight, you’ll sink.",
      "You're not better than anyone else, so work harder!",
      "The comfort zone is the death of your dreams. Get out and fight!",
      "No one will give you anything. You must earn everything yourself.",
      "Don't look back. The only way is forward, and full speed ahead.",
      "Every failure is a lesson. Don't let it bring you down.",
      "Stop dreaming and start acting. There's no time to waste.",
      "Don't live for others, live for yourself.",
      "Things won’t get better unless you do.",
      "If you want it, fight for it. It won't be easy.",
      "The only limit you have is the one you set yourself.",
      "Life will never be fair. You have to fight for it.",
      "If you stop striving for the best, you give up.",
      "Every decision you make brings you closer to your goal.",
      "Don’t be a spectator in your life. Be the main character.",
      "If you're not willing to fight for your dreams, they'll never come true.",
      "The time you invest today will pay off tomorrow.",
      "Success requires hard work and dedication. Take it seriously.",
      "The future belongs to those who act today.",
      "Believe in yourself, even when no one else does.",
      "The pain of failure is better than the pain of regret.",
      "Be relentless in your pursuit of success.",
      "When you fail, get back up and keep fighting.",
      "The only way to be successful is to never give up.",
      "Your success starts with your belief in yourself.",
      "If you want something, do it. Don’t let anything stop you.",
      "Every second counts. Use them wisely.",
      "The best things in life are the ones you fight for yourself.",
      "If you don't do what's necessary, you'll regret it.",
      "Don’t look at others, focus on your own path.",
      "You are the creator of your own reality.",
      "Life isn't easy. You have to fight for it.",
      "Stop with the excuses. Start taking action.",
      "Be the one who fights for their success.",
      "Every day is a new chance to get better.",
      "If you're not willing to make sacrifices, you'll never grow.",
      "Success is the result of hard work and persistence.",
      "Don’t let anyone tell you that you can't do it. Prove them wrong!",
      "If you really want something, you'll do whatever it takes to get it.",
      "The difference between success and failure is attitude.",
      "Success is not a destination, it’s a journey.",
      "The world is full of opportunities. Seize them!",
      "The decision to succeed is yours alone.",
      "Don't wait for the right moment. Create it yourself.",
      "Every step you take brings you closer to your goals.",
      "If you don’t change things, everything stays the same.",
      "Believe in your dreams, even if they seem unrealistic.",
      "You are responsible for your own happiness. Take control.",
      "Success comes to those who are willing to work hard.",
      "Don’t just watch, be the one who plays the game.",
      "Leave doubts behind. Believe in yourself!",
      "Your future depends on what you do today.",
      "If you want it, fight for it. It won’t be easy.",
      "Stop waiting. The time is now!",
      "You are the only person who can make your dreams come true.",
      "Every decision you make today will shape your tomorrow.",
      "If you're not willing to fight, you'll lose.",
      "Take control of your life and make something great out of it.",
      "If you're not willing to give everything, you won't achieve anything.",
      "Be the one who fights for their dreams. No one else will.",
      "Make the most of every day. You never know what tomorrow brings.",
      "If you're looking for happiness, start with yourself.",
      "Don’t be the reason you’re not successful.",
      "The challenges you face are your teachers.",
      "If you don’t push yourself, you won't grow.",
      "Life is full of battles. Fight and win!",
      "If you set a goal, never give up.",
      "There is no substitute for hard work and determination.",
      "You're not here to play. You're here to win. Do it or leave it.",
      "If you're not ready to give it your all, you'll never succeed.",
      "Success is no accident. It's the price for your sleepless nights.",
      "The world is a tough place. If you don’t fight, you’ll sink.",
      "You're not better than anyone else, so work harder!",
      "The comfort zone is the death of your dreams. Get out and fight!",
      "No one will give you anything. You must earn everything yourself.",
      "Don't look back. The only way is forward, and full speed ahead.",
      "Every failure is a lesson. Don't let it bring you down.",
      "Stop dreaming and start acting. There's no time to waste.",
      "Don't live for others, live for yourself.",
      "Things won’t get better unless you do.",
      "If you want it, fight for it. It won't be easy.",
      "The only limit you have is the one you set yourself.",
      "Life will never be fair. You have to fight for it.",
      "If you stop striving for the best, you give up.",
      "Every decision you make brings you closer to your goal.",
      "Don’t be a spectator in your life. Be the main character.",
      "If you're not willing to fight for your dreams, they'll never come true.",
      "The time you invest today will pay off tomorrow.",
      "Success requires hard work and dedication. Take it seriously.",
      "The future belongs to those who act today.",
      "Believe in yourself, even when no one else does.",
      "The pain of failure is better than the pain of regret.",
      "Be relentless in your pursuit of success.",
      "When you fail, get back up and keep fighting.",
      "The only way to be successful is to never give up.",
      "Your success starts with your belief in yourself.",
      "If you want something, do it. Don’t let anything stop you.",
      "Every second counts. Use them wisely.",
      "The best things in life are the ones you fight for yourself.",
      "If you don't do what's necessary, you'll regret it.",
      "Don’t look at others, focus on your own path.",
      "You are the creator of your own reality.",
      "Life isn't easy. You have to fight for it.",
      "Stop with the excuses. Start taking action.",
      "Be the one who fights for their success.",
      "Every day is a new chance to get better.",
      "If you're not willing to make sacrifices, you'll never grow.",
      "Success is the result of hard work and persistence.",
      "Don’t let anyone tell you that you can't do it. Prove them wrong!",
      "If you really want something, you'll do whatever it takes to get it.",
      "The difference between success and failure is attitude.",
      "Success is not a destination, it’s a journey.",
      "The world is full of opportunities. Seize them!",
      "The decision to succeed is yours alone.",
      "Don't wait for the right moment. Create it yourself.",
      "Every step you take brings you closer to your goals.",
      "If you don’t change things, everything stays the same.",
      "Believe in your dreams, even if they seem unrealistic.",
      "You are responsible for your own happiness. Take control.",
      "Success comes to those who are willing to work hard.",
      "Don’t just watch, be the one who plays the game.",
      "Leave doubts behind. Believe in yourself!",
      "Your future depends on what you do today.",
      "If you want it, fight for it. It won’t be easy.",
      "Stop waiting. The time is now!",
      "You are the only person who can make your dreams come true.",
      "Every decision you make today will shape your tomorrow.",
      "If you're not willing to fight, you'll lose.",
      "Take control of your life and make something great out of it.",
      "If you're not willing to give everything, you won't achieve anything.",
      "Be the one who fights for their dreams. No one else will.",
      "Make the most of every day. You never know what tomorrow brings.",
      "If you're looking for happiness, start with yourself.",
      "Don’t be the reason you’re not successful.",
      "The challenges you face are your teachers.",
      "If you don’t push yourself, you won't grow.",
      "Life is full of battles. Fight and win!",
      "If you set a goal, never give up.",
      "There is no substitute for hard work and determination."
    ];
  }
}
