import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MotivationQuotesService {

  constructor() { }

  GetQuote(): string {
    const list = this.getQuotes();
    const i = this.getRandomArbitrary(list.length)
    return list[i];
  }

  private getRandomArbitrary(max: number) {
    return Math.floor(Math.random() * max);
  }

  private getQuotes() {
    return [
      // Gym/Fitnessstudio
      "Trainiere so hart, dass selbst dein Körper Angst vor dir hat.",
      "Schmerz ist Schwäche, die den Körper verlässt. Komm schon, gib nicht auf!",
      "Du bist nicht hier, um Spaß zu haben. Du bist hier, um zu leiden und zu wachsen.",
      "Die einzige Zeit, die du beim Training vergeudest, ist die Zeit, in der du nicht trainierst.",
      "Wenn du denkst, dass du nicht mehr kannst, hast du noch 40 % in dir.",
      "Jeder Satz, den du machst, ist ein Schritt näher an deinem perfekten Körper.",
      "Dein einziger Feind im Fitnessstudio bist du selbst. Besiege dich selbst!",
      "Schau in den Spiegel. Das ist dein größter Konkurrent. Mach ihn fertig.",
      "Wenn du nicht schwitzt, hast du nicht hart genug gearbeitet.",
      "Entweder du bist der Beste oder du bist nichts. Es gibt kein Mittelmaß.",
      "Schmerz ist temporär. Der Stolz ist für immer.",
      "Trainiere hart, bleib demütig. Aber vor allem, trainiere hart.",
      "Wenn du nicht aufgeben kannst, kannst du auch nicht verlieren.",
      "Stärke wächst nicht aus körperlicher Kraft. Sie wächst aus unüberwindbaren Herausforderungen.",
      "Wenn du nicht bereit bist zu leiden, bist du nicht bereit, Erfolge zu ernten.",
      "Die einzige Grenze, die du hast, ist die, die du dir selbst setzt.",
      "Du hast keine Ausreden. Nur Ergebnisse.",
      "Wenn du aufgibst, wird jemand anderes deinen Erfolg feiern.",
      "Die Motivation wird dich nur bis zur Tür bringen. Die Disziplin bringt dich hinein.",
      "Erfolg kommt zu denen, die hart dafür arbeiten.",
      "Ziele sind nur Wünsche, wenn du keinen Plan hast.",
      "Wenn es einfach wäre, würde es jeder tun.",
      "Mach jeden Tag einen Schritt in die richtige Richtung.",
      "Leidenschaft ist der Kraftstoff, der deinen Erfolg antreibt.",
      "Warte nicht auf den perfekten Moment. Nimm den Moment und mach ihn perfekt.",
      "Wenn du etwas willst, musst du bereit sein, dafür zu kämpfen.",
      "Wenn du die Dinge ändern willst, musst du die Dinge ändern.",
      "Der Unterschied zwischen einem Traum und einem Ziel ist die Disziplin.",
      "Stärke ist das Ergebnis ständiger Anstrengung.",
      "Wenn du aufhörst zu kämpfen, wirst du aufhören zu gewinnen.",
      "Jeder Tropfen Schweiß ist ein Schritt näher an deinem Ziel.",
      "Deine Grenzen existieren nur in deinem Kopf.",
      "Wenn du nicht bereit bist zu leiden, bist du nicht bereit, Erfolg zu haben.",
      "Gib niemals auf, denn du weißt nie, wie nah du am Ziel bist.",
      "Sei stärker als deine stärkste Ausrede.",
      "Gib alles oder gib nichts.",
      "Dein Körper kann alles tun. Es ist dein Geist, den du überzeugen musst.",
      "Wenn du immer wieder das Gleiche tust, wirst du immer wieder die gleichen Ergebnisse erhalten.",
      "Du bist hier, um das Unmögliche möglich zu machen.",
      "Deine Ausreden sind die Ketten, die dich zurückhalten.",
      "Stark sein bedeutet nicht, niemals zu fallen. Es bedeutet, immer wieder aufzustehen.",
      "Wenn du nicht bereit bist, dich zu ändern, wirst du nie wachsen.",
      "Dein Körper ist ein Tempel. Behandle ihn mit Respekt.",
      "Der einzige Weg, um zu versagen, ist, es nicht zu versuchen.",
      "Lege den Schalter um und werde die beste Version von dir selbst.",
      "Der Schmerz, den du heute fühlst, wird die Stärke sein, die du morgen fühlst.",
      "Wenn du kämpfen musst, um zu gewinnen, dann kämpfe!",
      "Es gibt keine Abkürzungen. Du musst den Weg gehen.",
      "Das Gewicht, das du hebst, ist nicht das Problem. Das Problem ist, dass du nicht aufhörst, es zu tun.",
      "Niemand kann dir den Erfolg nehmen, den du dir erkämpft hast.",
      "Gib jedem Satz 110 %. Du bist mehr als fähig.",
      "Der einzige Grund, warum du nicht trainierst, ist, weil du nicht willst.",
      "Jeder Tag ist ein neuer Kampf. Sei bereit, ihn zu gewinnen.",
      "Das einzige, was zwischen dir und deinem Ziel steht, ist die Angst zu scheitern.",
      "Glaube an dich selbst, auch wenn sonst niemand an dich glaubt.",
      "Der einzige schlechte Satz ist der, den du nicht gemacht hast.",
      "Niemand wird für dich trainieren. Das ist dein Job.",
      "Harte Arbeit schlägt Talent, wenn Talent nicht hart arbeitet.",
      "Mach das Unmögliche möglich.",
      "Die Leute fragen sich, wie du es machst. Du weißt, dass es die Hingabe ist.",
      "Wenn du nicht bereit bist, alles zu geben, dann gib lieber nichts.",
      "Du bist stärker als du denkst. Glaub daran.",
      "Es gibt keine Grenzen, außer denen, die du dir selbst setzt.",
      "Wenn du aufhörst, wirst du nichts erreichen.",
      "Entscheide dich heute, besser zu sein als gestern.",
      "Wenn du nicht jeden Tag an dir arbeitest, arbeitest du gegen dich selbst.",
      "Der einzige Wettbewerb, den du hast, bist du selbst.",
      "Schau nicht auf das Ergebnis, schau auf den Prozess.",
      "Ein Champion ist jemand, der niemals aufgibt.",
      "Warte nicht auf die Motivation, erschaffe sie dir selbst.",
      "Die Wahrheit ist, dass es niemanden gibt, der für dich kämpfen wird. Du musst es selbst tun.",
      "Mach es für dich selbst. Du verdienst es.",
      "Jede Wiederholung bringt dich näher an dein Ziel.",
      "Der einzige Weg, um wirklich zu wachsen, ist, dich selbst herauszufordern.",
      "Niemand hat gesagt, dass es einfach wird. Du musst kämpfen!",
      "Du bist der Architekt deiner eigenen Zukunft.",
      "Die Leute bewundern deine Erfolge, aber sie wissen nicht, wie viel du dafür gekämpft hast.",
      "Wenn du nicht zu 100 % investierst, wird der Erfolg ausbleiben.",
      "Dein Körper wird nicht besser, wenn du nichts tust.",
      "Sei nicht bereit, einfach nur zu überleben. Sei bereit, zu gedeihen.",
      "Es ist nicht nur das Training, es ist eine Lebensweise.",
      "Entscheide dich für Erfolg oder entscheide dich für Scheitern.",
      "Du kannst alles erreichen, wenn du bereit bist, dafür zu arbeiten.",
      "Wenn du Erfolg willst, musst du die Dunkelheit durchqueren.",
      "Harte Arbeit ist der Schlüssel zum Erfolg. Mach es zur Gewohnheit.",
      "Die Leute werden dich beobachten. Sei der Grund, warum sie aufhören.",

      // Jurastudium
      "Der einzige Grund, warum du im Jurastudium scheiterst, ist, weil du nicht hart genug arbeitest.",
      "Jurastudium ist kein Spaß. Es ist Krieg. Geh rein und kämpfe!",
      "Jura ist nicht für Feiglinge. Entweder du kämpfst, oder du verlierst alles.",
      "Ein guter Jurist ist wie ein Raubtier – er geht nicht einfach davon, er nimmt, was ihm zusteht.",
      "Wenn du denkst, dass du alles weißt, bist du auf dem Holzweg. Jeder Fall ist eine neue Herausforderung.",
      "Die Gesetze sind da, um gebrochen zu werden. Sei derjenige, der sie bricht.",
      "Du wirst kein erfolgreicher Anwalt, wenn du nicht bereit bist, alles zu opfern.",
      "Die Bibliothek ist dein Schlachtfeld. Je mehr du weißt, desto besser bist du im Krieg.",
      "Wenn du nicht bereit bist, die Nacht durchzuarbeiten, wirst du niemals die Ernte einfahren.",
      "Es gibt keine Ausreden im Jurastudium. Entweder du machst es, oder du versagst.",
      "Schau nicht zurück, es gibt nichts, was du ändern kannst.",
      "Ein Anwalt, der nicht liest, ist wie ein Soldat ohne Waffe.",
      "Lerne, bis es schmerzt. Dann lerne weiter.",
      "Du bist nicht hier, um zu entspannen. Du bist hier, um zu lernen und zu kämpfen.",
      "Jura ist ein Marathon, kein Sprint. Bereite dich darauf vor, durchzuhalten.",
      "Wenn du kein Opfer bringen kannst, wirst du niemals die Krone tragen.",
      "Der Druck ist ein Teil des Spiels. Lern, damit umzugehen.",
      "Erfolg ist nicht für die Schwachen. Es ist für die, die bereit sind zu kämpfen.",
      "Wenn du scheiterst, lerne daraus und komm stärker zurück.",
      "Niemand wird dir etwas schenken. Du musst es dir verdienen.",
      "Der Erfolg im Jurastudium kommt nicht über Nacht.",
      "Die Herausforderungen sind die Bausteine deines Erfolgs.",
      "Du bist nicht hier, um zu träumen. Du bist hier, um zu handeln.",
      "Ein guter Anwalt kennt das Gesetz. Ein großartiger Anwalt kennt die Menschen.",
      "Wenn du nicht bereit bist, das Unmögliche zu versuchen, wirst du niemals erfolgreich sein.",
      "Die Konkurrenz ist hart. Sei härter.",
      "Jede Stunde, die du investierst, bringt dich deinem Ziel näher.",
      "Sei unnachgiebig in deinem Streben nach Wissen.",
      "Die Zeit für Entschuldigungen ist vorbei. Jetzt ist die Zeit zu lernen.",
      "Dein Studium wird dich nicht formen, es wird dich brechen oder stärken.",
      "Die Herausforderungen, denen du gegenüberstehst, sind die Prüfungen deines Charakters.",
      "Verliere nie den Glauben an deine Fähigkeiten.",
      "Sei der Anwalt, den du selbst gerne hättest.",
      "Die Zeit ist jetzt. Lass keine Gelegenheit verstreichen.",
      "Jede Stunde, die du schläfst, ist eine Stunde, die du deiner Konkurrenz gibst.",
      "Wenn du nicht bereit bist, die Arbeit zu investieren, wirst du es bereuen.",
      "Echte Anwälte scheuen sich nicht vor harter Arbeit.",
      "Die einzige Möglichkeit, im Jurastudium zu gewinnen, ist, niemals aufzugeben.",
      "Harte Arbeit und Hingabe sind der Schlüssel zum Erfolg.",
      "Wenn du im Jurastudium scheiterst, scheiterst du im Leben.",
      "Die Gesetze sind nicht einfach. Arbeite, um sie zu verstehen.",
      "Du bist nicht allein. Jeder kämpft. Sei besser als die anderen.",
      "Wenn du aufgibst, wirst du für immer im Schatten deiner Träume leben.",
      "Jeder Fall ist eine Gelegenheit, zu wachsen und zu lernen.",
      "Hör nicht auf zu kämpfen, nur weil es schwierig wird.",
      "Erfolg ist das Resultat von Ausdauer und harter Arbeit.",
      "Schau nie zurück. Der Weg nach vorne ist der einzige, der zählt.",
      "Wenn du nicht für deine Träume kämpfst, wirst du für die Träume anderer arbeiten.",
      "Der beste Anwalt ist der, der sich nie zufrieden gibt.",
      "Die besten Erfolge kommen von den Menschen, die sich den Herausforderungen stellen.",
      "Die Herausforderungen im Jurastudium sind die Treppen zu deinem Erfolg.",
      "Es gibt keine Abkürzungen zum Erfolg. Arbeite hart!",

      // Lebensverbesserung/Motivation
      "Du bist nicht hier, um zu spielen. Du bist hier, um zu gewinnen. Mach es oder lass es sein.",
      "Wenn du nicht bereit bist, alles zu geben, wirst du nie Erfolg haben.",
      "Erfolg ist kein Zufall. Es ist der Preis für deinen schlaflosen Nächte.",
      "Die Welt ist ein harter Ort. Wenn du nicht kämpfst, wirst du untergehen.",
      "Du bist nicht besser als die anderen, also arbeite härter!",
      "Die Komfortzone ist der Tod deiner Träume. Raus da und kämpfe!",
      "Niemand wird dir etwas schenken. Du musst alles selbst erarbeiten.",
      "Schau nicht zurück. Der einzige Weg ist vorwärts, und zwar mit voller Geschwindigkeit.",
      "Jede Niederlage ist eine Lektion. Lass nicht zu, dass sie dich runterzieht.",
      "Hör auf zu träumen und fang an zu handeln. Es gibt keine Zeit zu verlieren.",
      "Lebe nicht für andere, sondern für dich selbst.",
      "Die Dinge werden nicht besser, wenn du es nicht tust.",
      "Wenn du es willst, kämpfe dafür. Es wird nicht einfach sein.",
      "Die einzige Grenze, die du hast, ist die, die du dir selbst setzt.",
      "Das Leben wird niemals fair sein. Du musst es erkämpfen.",
      "Wenn du aufhörst, nach dem Besten zu streben, gibst du auf.",
      "Jede Entscheidung, die du triffst, bringt dich näher an dein Ziel.",
      "Sei nicht der Zuschauer deines Lebens. Sei der Hauptdarsteller.",
      "Wenn du nicht bereit bist, für deine Träume zu kämpfen, werden sie nie wahr.",
      "Die Zeit, die du heute investierst, wird sich morgen auszahlen.",
      "Erfolg erfordert harte Arbeit und Hingabe. Nimm es ernst.",
      "Die Zukunft gehört denen, die heute handeln.",
      "Glaube an dich selbst, auch wenn sonst niemand an dich glaubt.",
      "Der Schmerz des Scheiterns ist besser als der Schmerz des Bedauerns.",
      "Sei unaufhörlich in deiner Suche nach Erfolg.",
      "Wenn du scheiterst, steh wieder auf und kämpfe weiter.",
      "Die einzige Möglichkeit, erfolgreich zu sein, ist, niemals aufzugeben.",
      "Dein Erfolg beginnt mit deinem Glauben an dich selbst.",
      "Wenn du etwas willst, tu es. Lass dich nicht aufhalten.",
      "Jede Sekunde zählt. Nutze sie weise.",
      "Die besten Dinge im Leben sind die, die du dir selbst erkämpfst.",
      "Wenn du die Dinge nicht tust, die nötig sind, wirst du es bereuen.",
      "Schau nicht auf andere, konzentriere dich auf deinen eigenen Weg.",
      "Du bist der Schöpfer deiner eigenen Realität.",
      "Das Leben ist kein Zuckerschlecken. Du musst dafür kämpfen.",
      "Mach Schluss mit den Ausreden. Fang an zu handeln.",
      "Sei derjenige, der für seinen Erfolg kämpft.",
      "Jeder Tag ist eine neue Chance, besser zu werden.",
      "Wenn du nicht bereit bist, Opfer zu bringen, wirst du niemals wachsen.",
      "Erfolg ist das Ergebnis von harter Arbeit und Beständigkeit.",
      "Lass niemanden dir sagen, dass du es nicht kannst. Zeig es ihnen!",
      "Wenn du wirklich etwas willst, wirst du alles tun, um es zu bekommen.",
      "Der Unterschied zwischen Erfolg und Misserfolg ist die Einstellung.",
      "Erfolg ist kein Ziel, sondern eine Reise.",
      "Die Welt ist voller Möglichkeiten. Nutze sie!",
      "Die Entscheidung, erfolgreich zu sein, liegt bei dir.",
      "Warte nicht auf den richtigen Moment. Mach ihn dir selbst.",
      "Jeder Schritt, den du machst, bringt dich näher zu deinen Zielen.",
      "Wenn du die Dinge nicht veränderst, bleibt alles beim Alten.",
      "Glaube an deine Träume, selbst wenn sie unrealistisch erscheinen.",
      "Du bist für dein eigenes Glück verantwortlich. Übernimm die Kontrolle.",
      "Der Erfolg kommt zu denen, die bereit sind, hart zu arbeiten.",
      "Sei nicht nur ein Zuschauer, sondern der, der das Spiel spielt.",
      "Lass die Zweifel hinter dir. Glaube an dich selbst!",
      "Deine Zukunft hängt von dem ab, was du heute tust.",
      "Wenn du es willst, kämpfe dafür. Es wird nicht einfach sein.",
      "Hör auf zu warten. Die Zeit ist jetzt!",
      "Du bist die einzige Person, die deine Träume verwirklichen kann.",
      "Jede Entscheidung, die du heute triffst, wird dein Morgen beeinflussen.",
      "Wenn du nicht bereit bist zu kämpfen, wirst du verlieren.",
      "Nimm dein Leben in die Hand und mache etwas Großartiges daraus.",
      "Wenn du nicht bereit bist, alles zu geben, wirst du nichts erreichen.",
      "Sei derjenige, der für seine Träume kämpft. Niemand sonst wird es tun.",
      "Mach das Beste aus jedem Tag. Du weißt nie, was morgen kommt.",
      "Wenn du nach Glück suchst, fang bei dir selbst an.",
      "Sei nicht der Grund, warum du nicht erfolgreich bist.",
      "Die Herausforderungen, denen du gegenüberstehst, sind deine Lehrmeister.",
      "Wenn du dich nicht anstrengst, wirst du nicht wachsen.",
      "Das Leben ist voller Kämpfe. Kämpfe und gewinne!",
      "Wenn du dir ein Ziel setzt, gib niemals auf.",
      "Es gibt keinen Ersatz für harte Arbeit und Entschlossenheit."
    ];
  }
}
